[project]
name = "homelab-config"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "py-nickel>=1.17.0",

    # Workspace
    "homelab-cluster",
    "homelab-common",
    "homelab-context",
    "homelab-dns",
    "homelab-model",
    "homelab-pulumi",
]

[build-system]
requires = ["uv_build>=0.11.19,<0.12.0"]
build-backend = "uv_build"

[tool.ruff]
extend = "../../pyproject.toml"
